// Styles/UI:
import "@/styles/globals.css";
import { cn } from "@/utils/cn";

// Layout:
import Header from "@/layout/header";

// Providers:
import { ThemeProvider } from "@/providers/theme";
import OtherProviders from "@/providers/others";

// Fonts:
import { Inter } from "next/font/google";
import localFont from "next/font/local";
const InterFont = Inter({
  subsets: ["latin"],
  variable: "--inter-font",
  weight: ["400", "900"],
  display: "swap",
  preload: true,
});
const jetBrainsMono = localFont({
  variable: "--jetBrainsMono-font",
  src: "../fonts/JetBrainsMono-Regular.woff2",
  weight: "500",
  display: "swap",
  preload: true,
});

// Metadata:
export const metadata = {
  title: "frame - Generate images with beautiful gradients.",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(
          `${InterFont.variable} h-screen w-screen bg-light font-sans text-mini text-sm text-dark antialiased dark:bg-dark dark:text-white`
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <OtherProviders>
            <Header />
            <main>{children}</main>
          </OtherProviders>
        </ThemeProvider>
      </body>
    </html>
  );
}
